import React from 'react';
import { View, Text, ScrollView, StyleSheet } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Colors } from '@/constants/colors';
import { Typography } from '@/constants/typography';
import { Spacing } from '@/constants/spacing';
import { ScreenHeader } from '@/components/shared';

const sections = [
  {
    title: '1. Terms of Service',
    body: 'By using Bayu, you agree to these terms. Bayu is a travel planning platform operated in Malaysia. The service is provided "as is" for personal travel planning and booking purposes. You must be at least 18 years old to create an account and make bookings.',
  },
  {
    title: '2. Bookings & Payments',
    body: 'All prices are displayed in Malaysian Ringgit (MYR) unless otherwise stated. Bookings are subject to availability and confirmation from our travel partners. Payment is processed securely through our payment partners including FPX, credit/debit cards, and supported e-wallets. Cancellation policies vary by booking type and provider.',
  },
  {
    title: '3. Privacy Policy',
    body: 'We collect personal information necessary to provide our travel planning services, including your name, email, travel preferences, and booking history. Your data is stored securely and is never sold to third parties. We may share necessary booking details with travel service providers to fulfill your reservations.',
  },
  {
    title: '4. Data Protection',
    body: 'In compliance with Malaysian Personal Data Protection Act 2010 (PDPA), your personal data is processed lawfully and stored securely. You have the right to access, correct, and request deletion of your personal data. Contact our support team for any data-related requests.',
  },
  {
    title: '5. AI-Generated Content',
    body: 'Itineraries and recommendations generated by our AI are suggestions based on available data. While we strive for accuracy, prices, availability, and conditions may change. Always verify details with service providers before making final arrangements.',
  },
  {
    title: '6. Limitation of Liability',
    body: 'Bayu acts as a travel planning facilitator and is not directly responsible for services provided by third-party travel operators, hotels, airlines, or activity providers. We recommend purchasing travel insurance for all trips.',
  },
];

export default function TermsScreen() {
  const insets = useSafeAreaInsets();

  return (
    <View style={[styles.container, { paddingTop: insets.top }]}>
      <ScreenHeader title="Terms & Privacy" />
      <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
        <Text style={styles.lastUpdated}>Last updated: 1 March 2026</Text>
        {sections.map((section, i) => (
          <View key={i} style={styles.section}>
            <Text style={styles.sectionTitle}>{section.title}</Text>
            <Text style={styles.sectionBody}>{section.body}</Text>
          </View>
        ))}
        <Text style={styles.footer}>
          For questions about these terms, contact support@bayutravel.my
        </Text>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  content: { padding: Spacing.base, paddingBottom: 100 },
  lastUpdated: { fontSize: Typography.sizes.sm, fontFamily: Typography.fonts.body, color: Colors.textTertiary, marginBottom: Spacing.lg },
  section: { marginBottom: Spacing.xl },
  sectionTitle: { fontSize: Typography.sizes.md, fontFamily: Typography.fonts.headingBold, color: Colors.text, marginBottom: Spacing.sm },
  sectionBody: { fontSize: Typography.sizes.base, fontFamily: Typography.fonts.body, color: Colors.textSecondary, lineHeight: 24 },
  footer: { fontSize: Typography.sizes.sm, fontFamily: Typography.fonts.body, color: Colors.textTertiary, textAlign: 'center', marginTop: Spacing.xl },
});
